.TH SIMSU 6 "January 2025" "Simsu 1.4.3" "Games Manual"

.SH "NAME"
simsu \- basic sudoku game

.SH "SYNOPSIS"
.B simsu
[options]

.SH "DESCRIPTION"
Simsu is a basic Sudoku game. You can switch between filling in notes
(pencil mode), or filling in answers (pen mode). To make it easier to
see where to place numbers, you can highlight all instances of a number.
You can also check your answers for correctness while playing. The game
stores your current notes and answers, so that you can pick up where you
left off the next time you play.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.

.SH "SEE ALSO"
.BR qt6options (7)

.SH "REPORTING BUGS"
Report bugs to <simsu@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2009-2025 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
