.TH "SIMSU" "6" "February 2014"

.SH "NAME"
simsu \- basic sudoku game

.SH "SYNOPSIS"
.PP
.B simsu

.SH "DESCRIPTION"
.PP
Simsu is a basic Sudoku game. You can switch between filling in notes
(pencil mode), or filling in answers (pen mode). To make it easier to
see where to place numbers, you can highlight all instances of a number.
You can also check your answers for correctness while playing. The game
stores your current notes and answers, so that you can pick up where you
left off the next time you play.

.SH "COPYRIGHT"
.PP
Copyright \(co 2014 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
